In [3]:
import numpy as np
a = np.arange(2)
b = np.arange(2, 5)
print(f"a has shape {a.shape}: {a}")
print(f"b has shape {b.shape}: {b}")
np.concatenate((a, b))

a has shape (2,): [0 1]
b has shape (3,): [2 3 4]


array([0, 1, 2, 3, 4])

In [9]:
c = np.arange(1, 5).reshape((2, 2))
print(f'a has shape {c.shape}: {c}', sep='\n')
np.concatenate((c, c))

a has shape (2, 2): [[1 2]
 [3 4]]


array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [10]:
np.concatenate((c, c), axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [18]:
print(a.reshape(1, 2), c)
print("New row:")
print(np.concatenate((c,a.reshape(1,2))))
print("New column:")
print(np.concatenate((c,a.reshape(2,1)), axis=1))

[[0 1]] [[1 2]
 [3 4]]
New row:
[[1 2]
 [3 4]
 [0 1]]
New column:
[[1 2 0]
 [3 4 1]]


In [23]:
print('b', b)
print(np.stack((b,b)))

b [2 3 4]
[[2 3 4]
 [2 3 4]]


In [24]:
np.stack((b,b), axis=1)

array([[2, 2],
       [3, 3],
       [4, 4]])

In [27]:
d=np.arange(12).reshape(6,2)
print("d:")
print(d)
d1,d2 = np.split(d, (2))
print("d1:")
print(d1)
print("d2:")
print(d2)

d:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
d1:
[[0 1]
 [2 3]
 [4 5]]
d2:
[[ 6  7]
 [ 8  9]
 [10 11]]


In [25]:
d=np.arange(12).reshape(2,6)
print("d:")
print(d)
parts=np.split(d, (2,3,5), axis=1)
for i, p in enumerate(parts):
    print("part %i:" % i)
    print(p)

d:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
part 0:
[[0 1]
 [6 7]]
part 1:
[[2]
 [8]]
part 2:
[[ 3  4]
 [ 9 10]]
part 3:
[[ 5]
 [11]]


### Exercise 2.12 (row and column vectors)
Create function get_row_vectors that returns a list of rows from the input array of shape (n,m), but this time the rows must have shape (1,m). Similarly, create function get_columns_vectors that returns a list of columns (each having shape (n,1)) of the input matrix .

Example: for a 2x3 input matrix

 [[5 0 3]
  [3 7 9]]
the result should be

Row vectors: 
[array([[5, 0, 3]]), array([[3, 7, 9]])]
Column vectors: 
[array([[5],
        [3]]), 
 array([[0],
        [7]]), 
 array([[3],
        [9]])]
The above output is basically just the returned lists printed with print. Only some whitespace is adjusted to make it look nicer. Output is not tested.

In [28]:
def get_row_vectors(matrix):
    n, m =  matrix.shape
    print(n, m)
    result = []
    for i in range(n):
        result.append(matrix[i].reshape((1, m)))
    return result
c = np.array([[5, 0, 3],[3, 7, 9]])
print(get_row_vectors(c))
def get_column_vectors(matrix):
    result = []
    n, m = matrix.shape
    for j in range(m):
        result.append(matrix[:, j].reshape((n,1)))
    return result
c = np.array([[5, 0, 3],[3, 7, 9]])
get_column_vectors(c)


2 3
[array([[5, 0, 3]]), array([[3, 7, 9]])]


[array([[5],
        [3]]),
 array([[0],
        [7]]),
 array([[3],
        [9]])]

## Exercise 2.13 (diamond)
Create a function diamond that returns a two dimensional integer array where the 1s form a diamond shape. Rest of the numbers are 0. The function should get a parameter that tells the length of a side of the diamond. Do this using the eye and concatenate functions of NumPy and array slicing.

Example of usage:

print(diamond(3))
[[0 0 1 0 0]
 [0 1 0 1 0]
 [1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]]
print(diamond(1))
[[1]]


In [3]:
import numpy as np
def diamond(n):
    if n <=0:
        return None
    if n == 1:
        return np.eye(1, dtype=int)
    upper_left = np.eye(n, dtype=int)
    upper_right = np.flip(upper_left, axis=1)
    return np.concatenate((upper_left, upper_right[:, 1:]), axis=1)
print(diamond(5))
print(diamond(1))

[[1 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 1 0 0]
 [0 0 0 1 0 1 0 0 0]
 [0 0 0 0 1 0 0 0 0]]
[[1]]


### Fast computation using universal functions

In [6]:
a=np.array([2.1, 5.0, 17.2])
a2=a*2
print(a2)

[ 4.2 10.  34.4]


In [7]:
b=np.array([-1, 3.2, 2.4])
print(-a**2 * b)

[   4.41   -80.    -710.016]


In [8]:
print(np.abs(b))
print(np.cos(b))
print(np.exp(b))
print(np.log2(np.abs(b)))

[1.  3.2 2.4]
[ 0.54030231 -0.99829478 -0.73739372]
[ 0.36787944 24.5325302  11.02317638]
[0.         1.67807191 1.26303441]


### Aggregations: max, min, sum, mean, standard deviation and more

In [9]:
np.random.seed(0)
a=np.random.randint(-100, 100, (4,5))
print(a)
print(f"Minimum: {a.min()}, maximum: {a.max()}")
print(f"Sum: {a.sum()}")
print(f"Mean: {a.mean()}, standard deviation: {a.std()}")

[[ 72 -53  17  92 -33]
 [ 95   3 -91 -79 -64]
 [-13 -30 -12  40 -42]
 [ 93 -61 -13  74 -12]]
Minimum: -91, maximum: 95
Sum: -17
Mean: -0.85, standard deviation: 58.39886557117355


In [10]:
np.random.seed(9)
b=np.random.randint(0, 10, (3,4))
print(b)
print("Column sums:", b.sum(axis=0))
print("Row sums:", b.sum(axis=1))

[[5 6 8 6]
 [1 6 4 8]
 [1 8 5 1]]
Column sums: [ 7 20 17 15]
Row sums: [25 19 15]


In [12]:
print(np.sum(b))
print(b.sum())


59
59


In [21]:
a = np.arange(1, 11)
b = np.arange(1, 11)
print('product',np.prod(a))
print('elementwise',np.multiply(a, b))
print('elementwise sum', np.matmul(a, b))

product 3628800
elementwise [  1   4   9  16  25  36  49  64  81 100]
elementwise sum 385


In [25]:
print(np.sum(a))
print(np.add(a, b))

55
[ 2  4  6  8 10 12 14 16 18 20]


In [26]:
np.subtract(a, b)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
vectors = np.array([[3, 4],[1, 1], [0, 5]])
print(np.sum(vectors, axis=0))
print(np.sum(vectors, axis=1))

[ 4 10]
[7 2 5]


### Exercise 2.14 (vector lengths)
Write function vector_lengths that gets a two dimensional array of shape (n,m) as a parameter. Each row in this array corresponds to a vector. The function should return an array of shape (n,), that has the length of each vector in the input. The length is defined by the usual Euclidean norm (Wikipedia). Don't use loops at all in your solution. Instead use vectorized operations. You must use at least the np.sum and the np.sqrt functions. You can't use the function scipy.linalg.norm. Test your function in the main function.

In [38]:
def vector_length(arr):
    squared_sum = np.sum(arr ** 2, axis=1)
    return np.sqrt(squared_sum)
if __name__ == '__main__':
    print(vector_length(vectors))

[5.         1.41421356 5.        ]


### Exercise 2.15 (vector angles)
Let x and y be m-dimensional vectors. The angle α between two vectors is defined by the equation
Write function vector_angles that gets two arrays X and Y with same shape (n,m) as parameters. Each row in the arrays corresponds to a vector. The function should return vector of shape (n,) with the corresponding angles between vectors of X and Y in degrees, not in radians. Again, don't use loops, but use vectorized operations.

Note: function np.arccos is only defined on the domain [-1.0,1.0]. If you try to compute np.arccos(1.000000001), it will fail. These kind of errors can occur due to use of finite precision in numerical computations. Force the argument to be in the correct range (clip method).

In [46]:
def vector_angles(v1, v2):
    dot_product = np.dot(v1, v2)
    length_v1 = np.linalg.norm(v1)
    length_v2 = np.linalg.norm(v2)
    length_prod = length_v1 * length_v2
    cos_angles = dot_product / length_prod
    cos_angles = np.clip(cos_angles, 1.0, -1.0)
    angles_radian = np.arccos(cos_angles)
    angles_degree = np.degrees(angles_radian)
    return angles_degree
arr = np.arange(1, 4)
arr1 = np.arange(3, 6)
vector_angles(arr, arr1)

180.0