In [2]:
import numpy as np
np.array([1, 2, 4])

array([1, 2, 4])

In [3]:
np.array([[2, 4], [6, 8]])

array([[2, 4],
       [6, 8]])

In [4]:
np.array([[[2, 3], [4, 6]]])

array([[[2, 3],
        [4, 6]]])

In [5]:
np.zeros((2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [6]:
np.full((2, 3), fill_value=5)

array([[5, 5, 5],
       [5, 5, 5]])

In [8]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
np.empty((2, 4))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 9.28843414e-321, 1.78019082e-306,
        1.37959740e-306]])

In [12]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [13]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [14]:
np.linspace(0, np.pi, 4)

array([0.        , 1.04719755, 2.0943951 , 3.14159265])

In [15]:
np.linspace(0, np.sin(np.rad2deg(2)), 5)

array([0.        , 0.24926743, 0.49853487, 0.7478023 , 0.99706973])

In [16]:
np.sin(np.rad2deg(2))

0.9970697330600953

## Arrays with random elements

In [18]:
np.random.random((2, 3)) # uniformly distributed between 0 and 1

array([[0.64674647, 0.90659523, 0.24456889],
       [0.17176606, 0.48232471, 0.07517577]])

In [21]:
np.random.normal(0, 1, (3, 4)) # Elements are normally distributed with mean 0 and standard deviation 1

array([[-1.22741541,  0.30920945, -0.1815738 ,  1.14645621],
       [ 0.12829536,  0.16098189, -2.86449221,  0.90324831],
       [-0.96624469,  0.77202248,  0.54459469, -0.2413427 ]])

In [22]:
np.random.randint(-2, 10, (3,4))  # Elements are uniformly distributed integers from the half-open interval [-2,10)

array([[ 6,  7,  4,  1],
       [ 0,  1,  7, -2],
       [ 6,  6,  9,  1]])

In [40]:
np.random.seed(0)
print(np.random.randint(0, 100, 12))
print(np.random.normal(0, 1, 10))


[44 47 64 67 67  9 83 21 36 87 70 88]
[-0.10321885  0.4105985   0.14404357  1.45427351  0.76103773  0.12167502
  0.44386323  0.33367433  1.49407907 -0.20515826]


In [46]:
new_generator = np.random.RandomState(seed=123)  # RandomState is a class, so we give the seed to its constructor
new_generator.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [47]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [49]:
def info(name, a):
    print(f"{name} has dim {a.ndim}, shape {a.shape}, size {a.size}, and dtype {a.dtype}:")
    print(a)
b=np.array([[1,2,3], [4,5,6]])
info("b", b)

b has dim 2, shape (2, 3), size 6, and dtype int32:
[[1 2 3]
 [4 5 6]]


In [50]:
c=np.array([b, b])          # Creates a 3-dimensional array
info("c", c)

c has dim 3, shape (2, 2, 3), size 12, and dtype int32:
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [51]:
d=np.array([[1,2,3,4]])                # a row vector
info("d", d)

d has dim 2, shape (1, 4), size 4, and dtype int32:
[[1 2 3 4]]


In [1]:
import numpy as np
np.random.RandomState(seed=123)
random_array = np.random.randint(1, 50, (2, 2))
def get_rows(array_dim):
    print(array_dim)
    return [array_dim[0, :], array_dim[1, :], ]
get_rows(random_array)

[[20  7]
 [32 11]]


[array([20,  7]), array([32, 11])]

In [2]:
def get_columns(array_dim):
    array_dim = array_dim.T
    print(array_dim)
    return [array_dim[0, :], array_dim[1, :], ]
get_columns(random_array)

[[20 32]
 [ 7 11]]


[array([20, 32]), array([ 7, 11])]

In [3]:
a = np.arange(1, 10)
a.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])