In [5]:
import numpy as np

a = np.array((3, 5, 6, 8))
b = np.array([1, 3, 4])
print(a)
print(b)
print(a[0])

[3 5 6 8]
[1 3 4]
3


In [11]:
c = np.array(((2, 3, 4), (5, 6, 7)))
print(c)
c[1, 0]
c[1, 1] = 0
c

[[2 3 4]
 [5 6 7]]


array([[2, 3, 4],
       [5, 0, 7]])

In [12]:
np.empty((3, 3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [2.00267682e-307, 2.67020407e-306, 1.42413555e-306],
       [1.78019082e-306, 1.37959740e-306, 2.29178686e-312]])

In [13]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.zeros((3, 3), dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
nums = np.array([3, 7])
print(nums)


[3 7]


In [19]:
np.zeros_like(nums)

array([0, 0])

In [20]:
np.arange(0, 4, 3)

array([0, 3])

In [24]:
x, dx = np.linspace(0, 4, 3, retstep=True)
print(x)
print(dx)

[0. 2. 4.]
2.0
