In [4]:
import numpy as np

a = np.array((3, 5, 6, 8))
b = np.array([1, 3, 4])
print(a)
print(b)
print(a[0])

[3 5 6 8]
[1 3 4]
3


In [5]:
c = np.array(((2, 3, 4), (5, 6, 7)))
print(c)
c[1, 0]
c[1, 1] = 0
c

[[2 3 4]
 [5 6 7]]


array([[2, 3, 4],
       [5, 0, 7]])

In [12]:
np.empty((3, 3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [2.00267682e-307, 2.67020407e-306, 1.42413555e-306],
       [1.78019082e-306, 1.37959740e-306, 2.29178686e-312]])

In [13]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.zeros((3, 3), dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
nums = np.array([3, 7])
print(nums)


[3 7]


In [19]:
np.zeros_like(nums)

array([0, 0])

In [20]:
np.arange(0, 4, 3)

array([0, 3])

In [6]:
x, dx = np.linspace(0, 4, 3, retstep=True)
print(x)
print(dx)

[0. 2. 4.]
2.0


In [9]:
np.linspace(0, 56,  30)

array([ 0.        ,  1.93103448,  3.86206897,  5.79310345,  7.72413793,
        9.65517241, 11.5862069 , 13.51724138, 15.44827586, 17.37931034,
       19.31034483, 21.24137931, 23.17241379, 25.10344828, 27.03448276,
       28.96551724, 30.89655172, 32.82758621, 34.75862069, 36.68965517,
       38.62068966, 40.55172414, 42.48275862, 44.4137931 , 46.34482759,
       48.27586207, 50.20689655, 52.13793103, 54.06896552, 56.        ])

In [7]:
import numpy as np
x, step = np.linspace(2, 45, 6, retstep=True)
print(step)
print(x[-1])
print(x[0])

8.6
45.0
2.0


In [11]:
x, step = np.linspace(3, 6, 2, retstep=True, endpoint=False)
print(x)
# note that the last element is not in the mix
print(step)

[3.  4.5]
1.5


In [12]:
np.fromfunction(lambda i, j: 3 * i + j + 1, (3, 3))

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [17]:
np.fromfunction(lambda i, j: 2 * i * j, (4, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  2.,  4.],
       [ 0.,  4.,  8.],
       [ 0.,  6., 12.]])

In [21]:
print(False * 1)

0


In [25]:
N, n = 101, 5
def divisible_by_five(i):
    is_truthy = (i % n == 0) & (i > 50)
    return (is_truthy) * 1

np.fromfunction(divisible_by_five, (N, ), dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1])

### ndarray Attributes for Introspection

In [47]:
a = np.array(((1, 0, 1), (0, 1, 0)))
print(a.shape) # 2 rows and 3 columns
print(a.ndim) # dimension: 2
print(a.size) # size: number of elements 6
print(a.dtype) # data type: int
print(a.data) # memory allocation

(2, 3)
2
6
int32


In [49]:
a = np.zeros((3,3), dtype='>f8')
b = np.zeros((3,3), dtype='<f')
c = np.empty((3,3), dtype='|S4')
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
dt = np.dtype('>f8')
print(dt)
a = np.array([0., 1., -2.], dtype=dt)
print(a)

>f8
[ 0.  1. -2.]


In [62]:
print(dt.str)
print(dt.name)
print(dt.itemsize)

>f8
float64
8


In [64]:
a = np.array([1.2345678, 2.5, 3.98663377377377])
print(a)

[1.2345678  2.5        3.98663377]


In [68]:
b = a.astype('float32')
b.astype('int8')

array([1, 2, 3], dtype=int8)

### Universal Functions (ufuncs)

In [75]:
a = np.linspace(1, 6, 4, dtype=int)
# a = a.astype('int')
print(a)

[1 2 4 6]


In [77]:
b = a ** 2
b

array([ 1,  4, 16, 36])

In [78]:
b - 1

array([ 0,  3, 15, 35])

In [79]:
np.sqrt(b - 1)

array([0.        , 1.73205081, 3.87298335, 5.91607978])

In [80]:
y = np.exp(-np.linspace(0., 2., 5))

In [81]:
np.sin(b - 1)

array([ 0.        ,  0.14112001,  0.65028784, -0.42818267])

In [85]:
x = np.array(((1, 2), (3, 4)))
x

array([[1, 2],
       [3, 4]])

In [87]:
y = x
x * y # Elementwise operation

array([[ 1,  4],
       [ 9, 16]])

In [88]:
# Dot product
x @ y

array([[ 7, 10],
       [15, 22]])

In [89]:
# Dot product
x.dot(y)

array([[ 7, 10],
       [15, 22]])

In [90]:
# Dot product
np.dot(x, y)

array([[ 7, 10],
       [15, 22]])

In [91]:
np.matmul(x, y)

array([[ 7, 10],
       [15, 22]])

In [2]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array((4,3, 4, 6, 10))
test = ~(a > 3) | (b >= 6)
print(test)
print(np.all(test))
print(np.any(test))


[ True  True  True  True  True]
True
True


In [13]:
a = np.arange(0, 5, dtype='f8')
a /= 0
a

C:\Users\Rabo Yusuf\AppData\Local\Temp\ipykernel_5520\3889364599.py:2: RuntimeWarning: divide by zero encountered in divide
  a /= 0
C:\Users\Rabo Yusuf\AppData\Local\Temp\ipykernel_5520\3889364599.py:2: RuntimeWarning: invalid value encountered in divide
  a /= 0


array([nan, inf, inf, inf, inf])

In [14]:
isnan = np.isnan(a)
isnan

array([ True, False, False, False, False])

In [16]:
isinf = np.isinf(a)
isinf

array([False,  True,  True,  True,  True])

In [17]:
isfinite = np.isfinite(a)
isfinite

array([False, False, False, False, False])

### Flatten and Ravel

In [13]:
a = np.array(((1, 2, 4), (3, 5, 6)))
print(a)
b = a.flatten()
print(b)
b[2] = 0
print('b', b)
print('a', a)

[[1 2 4]
 [3 5 6]]
[1 2 4 3 5 6]
b [1 2 0 3 5 6]
a [[1 2 4]
 [3 5 6]]


In [20]:
a = np.array(((34, 66, 78), (78, 45, 23)))
print(a)
b = a.ravel()
print(b)
b[2] = 0
print('b', b)
print('a', a)

[[34 66 78]
 [78 45 23]]
[34 66 78 78 45 23]
b [34 66  0 78 45 23]
a [[34 66  0]
 [78 45 23]]


### Resize and Reshape

In [24]:
a = np.linspace(1, 4, 4)
print(a)
a.resize(2, 2)
print(a)

[1. 2. 3. 4.]
[[1. 2.]
 [3. 4.]]


In [26]:
a[1, 1] = -45
print('a', a)

a [[  1.   2.]
 [  3. -45.]]


In [33]:
a = np.linspace(1, 4, 4)
print(a)
b = a.reshape(2, 2)
print(b)
b[1, 1] = 90
print(a)
print(b)

[1. 2. 3. 4.]
[[1. 2.]
 [3. 4.]]
[ 1.  2.  3. 90.]
[[ 1.  2.]
 [ 3. 90.]]


### Transposing Array

In [35]:
a = np.linspace(1, 6, 6).reshape(3, 2)
print(a)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [36]:
print(a.T)

[[1. 3. 5.]
 [2. 4. 6.]]


In [37]:
print(a.transpose())

[[1. 3. 5.]
 [2. 4. 6.]]


In [40]:
b = np.linspace(1, 6, 6, dtype=int)
print(b)
print(b.T)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


### Merging and Splitting Arrays

In [49]:
a = np.array([0, 0, 0])
b = np.array([1, 1, 1])
c = np.array([2, 2, 2])
vstack = np.vstack((a, b, c))
print(vstack)

[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [50]:
hstack = np.hstack((a, b, c))
print(hstack)

[0 0 0 1 1 1 2 2 2]


In [51]:
dstack = np.dstack((a, b, c))
print(dstack)

[[[0 1 2]
  [0 1 2]
  [0 1 2]]]


In [61]:
a = np.linspace(1, 20, 9, dtype=int)
print(a)

[ 1  3  5  8 10 12 15 17 20]


In [64]:
x = np.hsplit(a, 3)
print(x)

[array([1, 3, 5]), array([ 8, 10, 12]), array([15, 17, 20])]


In [65]:
a = np.linspace(1, 20, 9, dtype=int).reshape((3, 3))
print(a)

[[ 1  3  5]
 [ 8 10 12]
 [15 17 20]]


In [69]:
x, y, z = np.hsplit(a, 3)
print(x)
print(y)
print(z)

[[ 1]
 [ 8]
 [15]]
[[ 3]
 [10]
 [17]]
[[ 5]
 [12]
 [20]]


In [73]:
a = np.linspace(1, 9, 9, dtype=int)
print(a)


[1 2 3 4 5 6 7 8 9]


In [4]:
import numpy as np
a = np.array([ 0, 1, 2, 3, 4, 5])
np.hsplit(a, (2, 3, 5))

[array([0, 1]), array([2]), array([3, 4]), array([5])]

### Indexing and Slicing an Array

In [8]:
a = np.linspace(1, 6, 6)
print(a)
a[1:4:2]

[1. 2. 3. 4. 5. 6.]


array([2., 4.])

In [9]:
print(a[3::-2])

[4. 2.]


In [11]:
a = np.linspace(1, 9, 9, dtype=int).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
a[2, 2]

9

In [13]:
a[1: -1, :]

array([[4, 5, 6]])

In [14]:
a[0:, -1:]

array([[3],
       [6],
       [9]])

In [16]:
a = np.linspace(0., 0.5, 6)
print(a)

[0.  0.1 0.2 0.3 0.4 0.5]


In [17]:
ia = [1, 4, 5]
print(a[ia])

[0.1 0.4 0.5]


In [23]:
a = np.linspace(1, 12, 12).reshape(4, 3)
ia = np.array( ((1, 2), (3, 3)) )
print(a[ia])

[[[ 4.  5.  6.]
  [ 7.  8.  9.]]

 [[10. 11. 12.]
  [10. 11. 12.]]]


In [24]:
a = np.array([90, 67, -3, 5])
ia = np.array([True, False, False, True])
a[ia]

array([90,  5])

In [25]:
years = np.array([1900, 1904, 1990, 1993, 2000, 2014, 2016, 2100])
leap_year = (years % 400 == 0) | (years % 4 == 0) & ~(years % 100 == 0)
print(list(zip(years , leap_year)))

[(1900, False), (1904, True), (1990, False), (1993, False), (2000, True), (2014, False), (2016, True), (2100, False)]


In [4]:
import numpy as np
a = np.linspace(1, 4, 4).reshape(2, 2)
print(a)
b = a[:, np.newaxis, :]
print(b)
print(b.shape)

[[1. 2.]
 [3. 4.]]
[[[1. 2.]]

 [[3. 4.]]]
(2, 1, 2)


### Meshes

In [9]:
x = np.linspace(0, 6, 6, dtype=int)
y = np.linspace(0, 4, 5, dtype=int)
X, Y = np.meshgrid(x, y)
print(X)

[[0 1 2 3 4 6]
 [0 1 2 3 4 6]
 [0 1 2 3 4 6]
 [0 1 2 3 4 6]
 [0 1 2 3 4 6]]


In [10]:
print(Y)

[[0 0 0 0 0 0]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [3 3 3 3 3 3]
 [4 4 4 4 4 4]]


In [11]:
X, Y = np.meshgrid(x, y, sparse=True)
print(X)

[[0 1 2 3 4 6]]


In [12]:
print(Y)

[[0]
 [1]
 [2]
 [3]
 [4]]


### Broadcasting

In [13]:
x = np.array([0, 2, 4, 5])
y = np.array([2, 4, 6, 7])
x * y

array([ 0,  8, 24, 35])

In [15]:
f = X * Y
print(f)

[[ 0  0  0  0  0  0]
 [ 0  1  2  3  4  6]
 [ 0  2  4  6  8 12]
 [ 0  3  6  9 12 18]
 [ 0  4  8 12 16 24]]


In [21]:
a = np.array([1, 2, 3])
b = np.array([0, 10, 100])
c = a[:, np.newaxis]
print(c)
print(c * b)

[[1]
 [2]
 [3]]
[[  0  10 100]
 [  0  20 200]
 [  0  30 300]]


In [5]:
import numpy as np
a = np.linspace(1, 10, 9, dtype=int).reshape(3, 3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [9]:
print(a.max())
print(a.min())
print(a.max(axis=0))
print(a.min(axis=1))

10
1
[ 7  8 10]
[1 4 7]


In [14]:
print(a.argmin())
print(a.argmax())
print(a.argmax(axis=0))
print(a.argmin(axis=1))

0
8
[2 2 2]
[0 0 0]


In [16]:
a = np.array([-1, 5, 2])
a.sort()
print(a)

[-1  2  5]


In [18]:
a = np.array([[2, 4, 5], [1, 5, -2]])
a.sort()
print(a)

[[ 2  4  5]
 [-2  1  5]]


In [22]:
a = np.array([90, 1000, -2, -1])
b = sorted(a, key=lambda x: x)
b

[-2, -1, 90, 1000]

In [28]:
c = np.array([45, 2, 4])
id_ = np.argsort(c)
print(id_)
d = c[id_]
d

[1 2 0]


array([ 2,  4, 45])

In [32]:
a = np.array([3, 5, 7])
ind = np.searchsorted(a, -1)
ind

0