In [3]:
import numpy as np
x = np.array([3, 6, 1])
y = np.arange(1, 4)
np.add(x, y)

array([4, 8, 4])

In [4]:
x + y

array([4, 8, 4])

In [5]:
x + 6

array([ 9, 12,  7])

In [7]:
z = np.ones((3, 3))
x + z

array([[4., 7., 2.],
       [4., 7., 2.],
       [4., 7., 2.]])

In [9]:
x.ndim

1

#### Broadcasting Example 1

In [14]:
M = np.ones((2, 3))
a = np.arange(3)
print(M.ndim)
print(a.ndim)

2
1


In [15]:
a.shape

(3,)

In [16]:
a.reshape(3, 1)

array([[0],
       [1],
       [2]])

In [17]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

#### Broadcasting Example 2


In [50]:
M = np.ones((2, 3))
a = np.arange(3)
M + a.reshape((1, 3))


array([[1., 2., 3.],
       [1., 2., 3.]])

In [57]:
print(M.reshape((6, 1)))
print(a.reshape((1, 3)))
M + a

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[0 1 2]]


array([[1., 2., 3.],
       [1., 2., 3.]])

In [4]:
import numpy as np
M = np.ones((2, 3))
a = np.arange(3).reshape((1, 3))
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [5]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])