### Comparision Masking

In [1]:
import numpy as np
a = np.arange(3)
b = np.array([0, 5, 3])
c = b > a
print(c)


[False  True  True]


In [5]:
np.any(c)

True

In [6]:
np.all(c)

False

In [7]:
np.sum(c)

2

In [22]:
import pandas as pd
data = pd.read_csv("https://raw.githubusercontent.com/csmastersUH/data_analysis_with_python_2020/master/kumpula-weather-2017.csv")

val = data['Air temperature (degC)'].values
print(np.sum(val < 0))
print(np.sum((0 < val) & (val > 0)))

49
314


In [25]:
c = val > 0
c

array([ True, False, False, False, False, False, False, False,  True,
        True, False, False,  True,  True, False, False, False,  True,
        True, False, False,  True,  True, False, False,  True,  True,
        True,  True,  True,  True, False, False, False,  True, False,
       False, False, False, False, False, False, False,  True,  True,
       False,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False,  True,  True,  True,  True, False,
       False, False, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [31]:
ten_greater_bool = c[:10]
print('first ten bool:', ten_greater_bool, sep='\n')
ten_greater_num = val[:10]
print('first ten num', ten_greater_num,sep='\n')

positive = ten_greater_num[ten_greater_bool]
print('return only the positive', positive)


first ten bool:
[ True False False False False False False False  True  True]
first ten num
[  0.6  -3.9  -6.5 -12.8 -17.8 -17.8  -3.8  -0.5   0.5   1.7]
return only the positive [0.6 0.5 1.7]


In [35]:
ten_greater_num[~ten_greater_bool] = 0
ten_greater_num

array([0.6, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5, 1.7])

In [4]:
import numpy as np

def columns_comparison(arr):
    compare = arr[:, 1] > arr[:,-2]
    print(arr[:, 1])
    print(arr[:, -2])
    return arr[compare]
arr = np.array([[8, 9, 3, 8, 8],
                    [0, 5, 3, 9, 9],
                    [5, 7, 6, 0, 4],
                    [7, 8, 1, 6, 2],
                    [2, 1, 3, 5, 8]])
columns_comparison(arr)

[9 5 7 8 1]
[8 9 0 6 5]


array([[8, 9, 3, 8, 8],
       [5, 7, 6, 0, 4],
       [7, 8, 1, 6, 2]])

In [5]:
def first_half_second_half(arr):
    # Calculate the number of columns in half
    m = arr.shape[1] // 2

    # Sum the first half of each row
    first_half_sum = np.sum(arr[:, :m], axis=1)

    # Sum the second half of each row
    second_half_sum = np.sum(arr[:, m:], axis=1)

    # Compare the sums and select the rows where the first half sum is larger
    result = arr[first_half_sum > second_half_sum]

    return result
a = np.array([[1, 3, 4, 2],
                  [2, 2, 1, 2]])
first_half_second_half(a)

array([[2, 2, 1, 2]])

In [10]:
np.random.seed(123)
a = np.array([8, 90, 21, 23])
a[[2, 1, 0]]

array([21, 90,  8])

In [25]:
a = np.random.randint(2, 4, 5)
print(a)
a[[0, 1]]

[2 3 2 2 2]


array([2, 3])

In [29]:
b=np.arange(16).reshape(4,4)
print(b)
row=np.array([0,2])
col=np.array([1,3])
print(b[row, col])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 1 11]


In [30]:
np.random.seed(0)
a=np.random.randint(0,10, (3,2))
b=np.random.randint(0,10, (2,4))
print(a)
print(b)

[[5 0]
 [3 3]
 [7 9]]
[[3 5 2 4]
 [7 6 8 8]]


In [31]:
np.matmul(a, b)

array([[ 15,  25,  10,  20],
       [ 30,  33,  30,  36],
       [ 84,  89,  86, 100]])

In [32]:
a @ b

array([[ 15,  25,  10,  20],
       [ 30,  33,  30,  36],
       [ 84,  89,  86, 100]])

In [33]:
s=np.array([[1, 6, 7],
 [7, 8, 1],
 [5, 9, 8]])
print("Original matrix:", s, sep="\n")
s_inv = np.linalg.inv(s)
print("Inverted matrix:", s_inv, sep="\n")
print("Matrix product:", s @ s_inv, sep="\n")                            # This should be pretty close to the identity matrix np.eye(3)
print("Matrix product the other way:", s_inv @ s, sep="\n")

Original matrix:
[[1 6 7]
 [7 8 1]
 [5 9 8]]
Inverted matrix:
[[-0.61111111 -0.16666667  0.55555556]
 [ 0.56666667  0.3        -0.53333333]
 [-0.25555556 -0.23333333  0.37777778]]
Matrix product:
[[ 1.00000000e+00 -2.77555756e-17  3.33066907e-16]
 [ 7.21644966e-16  1.00000000e+00  1.11022302e-16]
 [ 0.00000000e+00 -2.22044605e-16  1.00000000e+00]]
Matrix product the other way:
[[ 1.00000000e+00 -5.55111512e-16  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00  8.88178420e-16]
 [ 1.11022302e-16 -3.33066907e-16  1.00000000e+00]]
