In [3]:
import numpy as np
x = np.array([90, 40, 9, 30, 80, 67, 39, 15, 33, 79])

In [4]:
[x[3], x[7], x[2]]

[30, 15, 9]

In [6]:
ind = [3, 7, 4]
x[ind]

array([30, 15, 80])

In [9]:
ind = np.array([[3, 7], [4, 5]])
x[ind]

array([[30, 15],
       [80, 67]])

In [17]:
x[np.array([3, 5, 8])]

array([30, 67, 33])

In [18]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

In [20]:
row[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [23]:
x = X[row[:, np.newaxis], col]
x

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [25]:
X[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [31]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] += 100
x

array([  0, 101, 102,   3, 104,   5,   6,   7, 108,   9])