In [3]:
import numpy as np
A = np.array([[0, 0.5], [-1, 2]])
A

array([[ 0. ,  0.5],
       [-1. ,  2. ]])

In [4]:
print(A * 4)

[[ 0.  2.]
 [-4.  8.]]


In [5]:
B = np.array([[2, -0.5], [3, 1.5]])
B

array([[ 2. , -0.5],
       [ 3. ,  1.5]])

In [6]:
A.dot(B)

array([[1.5 , 0.75],
       [4.  , 3.5 ]])

In [7]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.linalg.matrix_power(A, 3) # A@A@A

array([[-1.  ,  1.75],
       [-3.5 ,  6.  ]])

### Note that the ** operator performs elementwise exponentiation:

In [9]:
A ** 3

array([[ 0.   ,  0.125],
       [-1.   ,  8.   ]])

In [18]:
theta = np.radians(30)
s, c = np.sin(theta), np.cos(theta)
A = np.array([[c, -s], [s, c]])
print(A)
r = np.array([1, 0])
np.dot(A, r)

[[ 0.8660254 -0.5      ]
 [ 0.5        0.8660254]]


array([0.8660254, 0.5      ])

### Frobenius norm for two-dimensional arrays

In [13]:
np.linalg.norm(A)

1.4142135623730951

### Euclidean norm for one-dimensional arrays

In [15]:
c = np.array([1, 3, 1])
np.linalg.norm(c)

3.3166247903554

In [16]:
np.linalg.det(A)

1.0

In [17]:
np.trace(A)

1.7320508075688774

In [19]:
np.linalg.matrix_rank(A) # Full ranking

2

In [22]:
x = np.array([[1, 3], [1, 3]])
np.linalg.matrix_rank(x)

1

### R−1RI = I = R−1V:

In [38]:
R = np.array([[50, 0, -30], [0, 40, -20], [-30, -20, 100]])
V = np.array([80, 80, 0])
I = np.linalg.inv(R) @ V
print(I)
print(np.linalg.solve(R, V))

[2.33333333 2.61111111 1.22222222]
[2.33333333 2.61111111 1.22222222]


In [30]:
B = np.array([[1, 3 - 1j], [3j, -1 + 1j]])
print(B)

[[ 1.+0.j  3.-1.j]
 [ 0.+3.j -1.+1.j]]


In [31]:
print(B.T)

[[ 1.+0.j  0.+3.j]
 [ 3.-1.j -1.+1.j]]


In [32]:
print(B.conj().T)

[[ 1.-0.j  0.-3.j]
 [ 3.+1.j -1.-1.j]]


In [33]:
print(np.linalg.inv(B))

[[-0.05-0.15j  0.05-0.35j]
 [ 0.3 +0.15j -0.05+0.1j ]]


In [35]:
vals, vecs = np.linalg.eig(B)
vals

array([ 2.50851535+2.09456868j, -2.50851535-1.09456868j])

In [36]:
vecs

array([[ 0.77468569+0.j        , -0.52924821+0.38116633j],
       [ 0.18832434+0.60365224j,  0.7580294 +0.j        ]])