In [58]:
import numpy as np
import pandas as pd

# Load the dataset from the CSV file
df = pd.read_csv('https://raw.githubusercontent.com/altair-viz/vega_datasets/master/vega_datasets/_data/seattle-weather.csv')
# Convert the 'date' column to datetime format
df['date'] = pd.to_datetime(df['date'])
# Filter for data from 2015
rainfall_2015 = df[df['date'].dt.year == 2015]['precipitation']
print(rainfall_2015)
# Convert to a NumPy array
rainfall_mm = np.array(rainfall_2015)

# Check the length of the resulting array
len(rainfall_mm)


1096     0.0
1097     1.5
1098     0.0
1099    10.2
1100     8.1
        ... 
1456     8.6
1457     1.5
1458     0.0
1459     0.0
1460     0.0
Name: precipitation, Length: 365, dtype: float64


365

In [6]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
x > 4

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [4]:
np.count_nonzero(x> 4)

4

In [5]:
print(x.shape)
u, z = x.shape
total = u * z
total

(3, 3)


9

In [6]:
np.sum(x > 4)

4

In [7]:
np.sum(x<=4)

5

In [9]:
np.sum(x<=4) + np.sum(x>4)

9

In [10]:
np.sum(x < 4, axis=1)

array([3, 1, 0])

In [11]:
np.any(x>15)

False

In [12]:
np.all(x<15)

True

In [17]:
np.all(x > 4, axis=0)

array([False, False, False])

In [23]:
y = 10
np.sum(y > -2)

1

In [28]:
y, z = 23, 0
np.sum((z == 0) | (y > 100))

1

In [44]:
rainfall_2015 > 0

1096    False
1097     True
1098    False
1099     True
1100     True
        ...  
1456     True
1457     True
1458    False
1459    False
1460    False
Name: precipitation, Length: 365, dtype: bool

In [60]:
days = np.arange(365)
rainy = (rainfall_2015 > 0)
summer = (days > 172) & (days < 262)
print("Median precip on rainy days in 2015 (mm): ", np.median(rainfall_mm[rainy]))
print("Median precip on summer days in 2015 (mm): ",
np.median(rainfall_mm[summer]))
print("Maximum precip on summer days in 2015 (mm): ",
np.max(rainfall_mm[summer]))
print("Median precip on non-summer rainy days (mm):",
np.median(rainfall_mm[rainy & ~summer]))

Median precip on rainy days in 2015 (mm):  3.8
Median precip on summer days in 2015 (mm):  0.0
Maximum precip on summer days in 2015 (mm):  32.5
Median precip on non-summer rainy days (mm): 4.1
