In [7]:
import numpy as np
nums = np.array([[2, 3], [4, 4]])
row = nums.reshape((1, 4))
row

array([[2, 3, 4, 4]])

In [9]:
col = nums.reshape((4, 1))
col

array([[2],
       [3],
       [4],
       [4]])

In [12]:
arr = np.arange(0, 9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
arr.reshape((1, 9))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [14]:
arr.reshape(9, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [15]:
arr[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [16]:
arr[np.newaxis, :]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
def get_row(two_dim):
    return [row for row in two_dim]
def get_col(two_dim):
    return [col for col in two_dim.T]
a = np.array([[5, 0, 3, 3],
 [7, 9, 3, 5],
 [2, 4, 7, 6],
 [8, 8, 1, 6]])


In [17]:
np.array([2, 3, 5]) # One dim

array([2, 3, 5])

In [18]:
np.array([[2, 43], [6, 8]]) # two dim

array([[ 2, 43],
       [ 6,  8]])

In [19]:
np.array([[[2, 3], [3, 5]]])

array([[[2, 3],
        [3, 5]]])

In [20]:
#helper functions
np.zeros((2, 3), dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [21]:
np.ones((2, 3), dtype='int')

array([[1, 1, 1],
       [1, 1, 1]])

In [23]:
np.full((2, 3), fill_value=8)

array([[8, 8, 8],
       [8, 8, 8]])

In [24]:
np.empty((2, 3))

array([[0.8, 0.8, 0.8],
       [0.8, 0.8, 0.8]])

In [25]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [30]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [35]:
np.linspace(1, np.pi, 10, endpoint=False)

array([1.        , 1.21415927, 1.42831853, 1.6424778 , 1.85663706,
       2.07079633, 2.28495559, 2.49911486, 2.71327412, 2.92743339])

In [37]:
np.random.random((2, 3))

array([[0.26269788, 0.95816082, 0.67056553],
       [0.16809149, 0.95457962, 0.00659031]])

In [41]:
np.random.normal(0, 1, (2, 3))

array([[ 1.3867537 ,  0.05999934, -2.43472317],
       [-0.2496975 ,  0.29235622,  0.40066902]])

In [42]:
np.random.normal(2, 4, (3, 3))

array([[ 4.11507718,  5.2692343 ,  6.39218553],
       [ 4.5324188 ,  4.47824636,  5.80343478],
       [ 4.4371995 , -1.51986152,  2.62313625]])

In [43]:
np.random.randint(1, 5, (3, 4))

array([[4, 3, 3, 1],
       [2, 2, 4, 2],
       [2, 1, 3, 2]])

In [44]:
np.random.seed(0)
print(np.random.randint(0, 100, 10))
print(np.random.normal(0, 1, 10))

[44 47 64 67 67  9 83 21 36 87]
[ 1.26611853 -0.50587654  2.54520078  1.08081191  0.48431215  0.57914048
 -0.18158257  1.41020463 -0.37447169  0.27519832]


In [45]:
new_generator = np.random.RandomState(seed=123)  # RandomState is a class, so we give the seed to its constructor
new_generator.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [46]:
def info(name, a):
    print(f"{name} has dim {a.ndim}, shape {a.shape}, size {a.size}, and dtype {a.dtype}:")
    print(a)

In [47]:
b=np.array([[1,2,3], [4,5,6]])
info("b", b)

b has dim 2, shape (2, 3), size 6, and dtype int32:
[[1 2 3]
 [4 5 6]]


In [48]:
a=np.arange(9)
anew=a.reshape(3,3)
info("anew", anew)
info("a", a)

anew has dim 2, shape (3, 3), size 9, and dtype int32:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
a has dim 1, shape (9,), size 9, and dtype int32:
[0 1 2 3 4 5 6 7 8]


In [52]:
a = np.arange(0, 4)
row = a.reshape((1, 4))
col = a.reshape((4, 1))


In [53]:
info('a', a)

a has dim 1, shape (4,), size 4, and dtype int32:
[0 1 2 3]


In [54]:
info('row', row)

row has dim 2, shape (1, 4), size 4, and dtype int32:
[[0 1 2 3]]


In [55]:
info('col', col)

col has dim 2, shape (4, 1), size 4, and dtype int32:
[[0]
 [1]
 [2]
 [3]]


In [57]:
info('col', a[:, np.newaxis])

col has dim 2, shape (4, 1), size 4, and dtype int32:
[[0]
 [1]
 [2]
 [3]]


In [58]:
info('row', a[np.newaxis, :])

row has dim 2, shape (1, 4), size 4, and dtype int32:
[[0 1 2 3]]


In [60]:
ab = np.arange(0, 4)
ab

array([0, 1, 2, 3])

In [61]:
bc = np.array([0, 67, 3])

In [62]:
np.concatenate((ab, bc))

array([ 0,  1,  2,  3,  0, 67,  3])

In [66]:
w = np.arange(1, 10).reshape(3, 3)
w


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
v = np.array([[3, 5, 8], [2, 4, 9]])

In [75]:
np.concatenate((w, v))


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [3, 5, 8],
       [2, 4, 9]])

In [78]:
t = np.arange(1, 13).reshape(2, 2, 3)
t

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [83]:
e = np.arange(1, 7).reshape(1, 2, 3)
np.concatenate((e, t))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [103]:
x = np.arange(1, 10).reshape(3, 3)
y = np.array([[2, 5, 4], [4, 6, 8], [0, 8, 1], [4, 6, 9], [7, 4, 6]])

In [104]:
np.concatenate((x, y))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 5, 4],
       [4, 6, 8],
       [0, 8, 1],
       [4, 6, 9],
       [7, 4, 6]])

In [105]:
s = np.arange(0, 5).reshape((1, 5))
c = s.reshape((5, 1))
c


array([[0],
       [1],
       [2],
       [3],
       [4]])

In [107]:
np.concatenate((c, y), axis=1)

array([[0, 2, 5, 4],
       [1, 4, 6, 8],
       [2, 0, 8, 1],
       [3, 4, 6, 9],
       [4, 7, 4, 6]])

###  stack 

In [110]:
a = np.arange(0, 4)
a

array([0, 1, 2, 3])

In [120]:
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [121]:
np.stack((a, b))

array([[0, 1, 2, 3],
       [1, 2, 3, 4]])

In [117]:
np.concatenate((a, b))

array([0, 1, 2, 3, 1, 2, 3, 4])

In [122]:
np.stack((a, b), axis= 1)

array([[0, 1],
       [1, 2],
       [2, 3],
       [3, 4]])

In [125]:
d = np.arange(0, 12).reshape((2, 6))
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [127]:
np.split(d, 2, axis=1)

[array([[0, 1, 2],
        [6, 7, 8]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11]])]

In [128]:
np.split(d, 2)

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]

In [139]:
def get_row_vectors(array):
    _, m = np.array(array).shape
    return [np.array(row).reshape(1, m) for row in array]
a = [[5, 0, 3],
  [3, 7, 9]]
print(get_row_vectors(a))
def get_column_vector(array):
    n, _ = np.array(array).shape
    return[np.array(col).reshape(n, 1) for col in np.array(array).T]
get_column_vector(a)

[array([[5, 0, 3]]), array([[3, 7, 9]])]


[array([[5],
        [3]]),
 array([[0],
        [7]]),
 array([[3],
        [9]])]

In [141]:
import numpy as np

def diamond(n):
    # Create the first half of the diamond using np.eye and concatenate
    upper = np.eye(n, dtype=int)
    lower = np.flipud(upper)

    # Combine to form the full diamond shape
    diamond_array = np.concatenate((upper, lower[1:]), axis=0)
    diamond_array = np.concatenate((diamond_array, np.fliplr(diamond_array[:, :-1])), axis=1)

    return diamond_array

# Test the function
print(diamond(3))
print(diamond(1))


[[1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]
 [0 1 0 1 0]
 [1 0 0 0 1]]
[[1]]


In [143]:
n = 3
a = np.eye(n)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [147]:
np.flipud(a)

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [148]:
np.random.seed(0)
a=np.random.randint(-100, 100, (4,5))
print(a)
print(f"Minimum: {a.min()}, maximum: {a.max()}")
print(f"Sum: {a.sum()}")
print(f"Mean: {a.mean()}, standard deviation: {a.std()}")

[[ 72 -53  17  92 -33]
 [ 95   3 -91 -79 -64]
 [-13 -30 -12  40 -42]
 [ 93 -61 -13  74 -12]]
Minimum: -91, maximum: 95
Sum: -17
Mean: -0.85, standard deviation: 58.39886557117355


In [149]:
np.random.seed(9)
b=np.random.randint(0, 10, (3,4))
print(b)
print("Column sums:", b.sum(axis=0))
print("Row sums:", b.sum(axis=1))

[[5 6 8 6]
 [1 6 4 8]
 [1 8 5 1]]
Column sums: [ 7 20 17 15]
Row sums: [25 19 15]


In [150]:
a=np.arange(1000)
%timeit np.sum(a)

4.03 µs ± 172 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [153]:
import numpy as np

def vector_lengths(vectors):
    """
    Calculate the Euclidean norm (length) of each vector in a 2D array.

    Parameters:
    vectors (numpy.ndarray): A 2D array of shape (n, m) where each row is a vector.

    Returns:
    numpy.ndarray: A 1D array of shape (n,) containing the length of each vector.
    """
    # Calculate the square of each element in the array
    squared_elements = np.square(vectors)

    # Sum the squared elements along each row (axis=1)
    sum_of_squares = np.sum(squared_elements, axis=1)

    # Calculate the square root of the sum of squares
    lengths = np.sqrt(sum_of_squares)

    return lengths

def main():
    # Test the function
    vectors = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    print(vector_lengths(vectors))

if __name__ == "__main__":
    main()

[ 3.74165739  8.77496439 13.92838828]


In [154]:
import numpy as np

def vector_angles(X, Y):
    """
    Calculate the angles between corresponding vectors in two arrays.

    Parameters:
    X (numpy.ndarray): A 2D array of shape (n, m) where each row is a vector.
    Y (numpy.ndarray): A 2D array of shape (n, m) where each row is a vector.

    Returns:
    numpy.ndarray: A 1D array of shape (n,) containing the angles between vectors in degrees.
    """
    # Calculate the inner product of corresponding vectors
    inner_products = np.sum(X * Y, axis=1)

    # Calculate the norms of vectors in X and Y
    norms_X = np.sqrt(np.sum(np.square(X), axis=1))
    norms_Y = np.sqrt(np.sum(np.square(Y), axis=1))

    # Calculate the cosine of the angles
    cos_angles = inner_products / (norms_X * norms_Y)

    # Clip the cosine values to the range [-1.0, 1.0] to avoid errors
    cos_angles = np.clip(cos_angles, -1.0, 1.0)

    # Calculate the angles in radians using arccos
    angles_radians = np.arccos(cos_angles)

    # Convert the angles from radians to degrees
    angles_degrees = np.degrees(angles_radians)

    return angles_degrees

def main():
    # Test the function
    X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    Y = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
    print(vector_angles(X, Y))

if __name__ == "__main__":
    main()

[28.03520167 18.54899961 28.03520167]


In [155]:
np.arange(3) + np.array([4])

array([4, 5, 6])

In [156]:
np.arange(3) + 4

array([4, 5, 6])

In [162]:
a=np.full((3,3), 5)
b=np.arange(3)
print("a:", a, sep="\n")
print("b:", b)
print("a+b:", a+b, sep="\n")

a:
[[5 5 5]
 [5 5 5]
 [5 5 5]]
b: [0 1 2]
a+b:
[[5 6 7]
 [5 6 7]
 [5 6 7]]


### comparison and masking

In [5]:
import numpy as np
a = np.array([5, 8, 4])
b = np.arange(2, 5)
print(a, b)

[5 8 4] [2 3 4]


In [8]:
c = a > b
c

array([ True,  True, False])

In [9]:
np.any(c)

True

In [10]:
np.all(c)

False

In [11]:
np.sum(c)

2

In [60]:
import pandas as pd
data = pd.read_csv("https://raw.githubusercontent.com/csmastersUH/data_analysis_with_python_2020/master/kumpula-weather-2017.csv")['Air temperature (degC)']

a = data.values.shape
b = data.values
print(a)
data_len = data.index

(365,)


In [62]:
print('sum less than zero ', np.sum(b < 0))
print('sum greater or equal to zero ', np.sum(b >= 0))
print(data_len)

sum less than zero  49
sum greater or equal to zero  316
RangeIndex(start=0, stop=365, step=1)


In [63]:
print('sum of greater than zero and less than ten: ', np.sum((b > 0) & (b < 10)))

sum of greater than zero and less than ten:  185


In [64]:
cb = b > 0
print(b[cb][:10])

[0.6 0.5 1.7 1.1 0.8 1.1 1.6 1.  0.1 1.9]


In [68]:
true = b > 0
b[~true] = 0
b

array([ 0.6,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0.5,  1.7,  0. ,
        0. ,  1.1,  0.8,  0. ,  0. ,  0. ,  1.1,  1.6,  0. ,  0. ,  1. ,
        0.1,  0. ,  0. ,  1.9,  1.6,  0.8,  0.6,  1. ,  0.2,  0. ,  0. ,
        0. ,  0.4,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1.5,
        4.4,  0. ,  0.5,  1.5,  1.9,  2.2,  0.4,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  2.1,  1.5,  1.5,  0.9,  0. ,  0. ,  0. ,  0. ,
        0.2,  1.2,  1.4,  2.2,  0. ,  0.6,  0.6,  3.8,  3.4,  2. ,  1.6,
        0.6,  0.2,  1.6,  2.3,  2.5,  0.5,  1.9,  4.8,  6.6,  2.4,  0.4,
        0. ,  0.2,  1.5,  4.3,  3. ,  3.8,  3.3,  4.7,  4.1,  3.3,  3.7,
        6. ,  4.3,  1.8,  1.2,  0. ,  0. ,  0. ,  0.6,  0.3,  1.2,  2.5,
        5.7,  3.1,  2.9,  3.6,  2.8,  3.2,  4.4,  4.1,  2.3,  2.2,  7.6,
        9.4,  9.2,  6.7, 10.1, 11.1,  6.1,  4.4,  1.5,  1.5,  2.9,  5.1,
        7.5,  9.8,  9. ,  7.3,  9.4, 11.2, 16.1, 16.9, 14.7, 14.6, 13.3,
       12.4, 14.1, 14.1,  9.6, 13.2, 14.1,  9.6, 10

In [71]:
def column_comparison(arr):
    # Compare the values in the second column (index 1) with the values in the second last column (index -2)
    result = arr[arr[:, 1] > arr[:, -2]]
    return result
array = np.array([[8, 9, 3, 8, 8],
                      [0, 5, 3, 9, 9],
                      [5, 7, 6, 0, 4],
                      [7, 8, 1, 6, 2],
                      [2, 1, 3, 5, 8]])
column_comparison(array)

array([[8, 9, 3, 8, 8],
       [5, 7, 6, 0, 4],
       [7, 8, 1, 6, 2]])

In [72]:
np.random.seed(0)
a=np.random.randint(0, 20,20)
a2=np.array([a[2], a[5], a[7]])
print(a)
print(a2)

[12 15  0  3  3  7  9 19 18  4  6 12  1  6  7 14 17  5 13  8]
[ 0  7 19]


In [73]:
idx=[2,5,7]           # List of indices
print(a[idx])         # In fancy indexing in place of a single index, we can provide a list of indices
print(a[[2,5,7]])     # Or directly

[ 0  7 19]
[ 0  7 19]


In [74]:
x = np.arange(0, 9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [75]:
idx = [0, 3, 5]
x[idx]

array([0, 3, 5])

In [78]:
idxx = [5, 7, 2]
x[idxx] = 0
x

array([0, 1, 0, 0, 4, 0, 6, 0, 8])

In [80]:
y = np.arange(16).reshape((4, 4))
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
row_idx = [1, 3]
col_idx = [0, 2]
print(y[row_idx])
print(y[col_idx])

[[ 4  5  6  7]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 8  9 10 11]]


In [86]:
# second row: fourth element
# first row: third element
y[row_idx, col_idx]

array([ 4, 14])

In [88]:
z = np.arange(1, 17).reshape((4, 4))
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [89]:
row2=np.array([[0, 0], [2,2]])
col2=np.array([[1,3], [1,3]])

In [90]:
z[row2, col2]

array([[ 2,  4],
       [10, 12]])

In [95]:
z[:, [0, 1]]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [100]:
a = np.array([90, 0, 6])
print(a)
np.sort(a)

[90  0  6]


array([ 0,  6, 90])

In [102]:
np.random.seed(45)
a = np.random.randint(0, 16, (4, 4))
a

array([[11, 14,  3, 12],
       [ 0, 15, 13,  5],
       [ 3,  4,  9,  8],
       [15,  1, 14,  5]])

In [105]:
b = np.sort(a, axis=0)
b

array([[ 0,  1,  3,  5],
       [ 3,  4,  9,  5],
       [11, 14, 13,  8],
       [15, 15, 14, 12]])

In [107]:
c = np.sort(b, axis=1)
c

array([[ 0,  1,  3,  5],
       [ 3,  4,  5,  9],
       [ 8, 11, 13, 14],
       [12, 14, 15, 15]])

In [108]:
a=np.array([23,12,47,35,59])
print("Array a:", a)
idx = np.argsort(a)
print("Indices:", idx)

Array a: [23 12 47 35 59]
Indices: [1 0 3 2 4]
