### Maxima and Minima

In [6]:
import numpy as np
a = np.sqrt(np.linspace(-2, 2, 4))
print(a)

[       nan        nan 0.81649658 1.41421356]


C:\Users\Rabo Yusuf\AppData\Local\Temp\ipykernel_8196\386165967.py:2: RuntimeWarning: invalid value encountered in sqrt
  a = np.sqrt(np.linspace(-2, 2, 4))


In [7]:
np.amin(a)

nan

In [8]:
np.amax(a)

nan

In [9]:
np.nanmin(a)

0.8164965809277259

In [10]:
np.nanmax(a)

1.4142135623730951

In [11]:
np.argmax(a)

0

In [12]:
np.argmin(a)

0

In [13]:
np.nanargmax(a)

3

In [14]:
np.nanargmin(a)

2

### Percentiles

In [16]:
a = np.array([[0., 0.6, 1.2], [1.8, 2.4, 3.0]])
np.percentile(a, 50)

1.5

In [17]:
np.percentile(a, 75)

2.25

In [18]:
np.percentile(a, 50, axis = 1)

array([0.6, 2.4])


### Averages, Variances and Correlations

In [20]:
x = np.array([1., 4., 9., 16.])
np.mean(x)

7.5

In [21]:
np.median(x)

6.5

In [22]:
np.average(x, weights=[0., 1, 2, 0.])

7.333333333333333

In [24]:
x = np.array( [[1., 8., 27], [-0.5, 1., 0.]] )
av, sw = np.average(x, weights=[0., 1., 0.1], axis=1, returned=True)
print(av)

[9.72727273 0.90909091]


In [25]:
sw

array([1.1, 1.1])

In [26]:
x = np.array([1., 2., 3., 4.])
np.std(x, ddof=1)

1.2909944487358056

In [29]:

x = np.array([[ 0.115 , 0.0575, -1.2325],
[ 0.0575, 3.757 , -0.8775],
[ -1.2325, -0.8775, 14.525 ]])
np.var(x, axis=1, ddof=1)

array([ 0.58052708,  6.00651925, 80.94363958])

In [30]:
print(np.corrcoef(x))

[[ 1.          0.62706916 -0.99983779]
 [ 0.62706916  1.         -0.64099741]
 [-0.99983779 -0.64099741  1.        ]]
