In [5]:
import numpy as np

x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
y = x.reshape((3,3))
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
xh = x.reshape((1, 9))
xh

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [12]:
xv = x.reshape((9, 1))
xv

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [14]:
x_new_h = x[np.newaxis, :]
x_new_h

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [16]:
x_new_v = x[:, np.newaxis]
x_new_v

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [20]:
two_dim = np.arange(0, 4).reshape((2, 2))
two_dim

array([[0, 1],
       [2, 3]])

##### Same dimension Concatenate 

In [21]:
#stack along the first axis
np.concatenate([two_dim, two_dim])

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [23]:
#stack along the second axis
np.concatenate((two_dim, two_dim), axis=1)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

In [45]:
one_dim = np.arange(1, 3)
one_dim

array([1, 2])

In [46]:
np.vstack((one_dim, two_dim))

array([[1, 2],
       [0, 1],
       [2, 3]])

In [30]:
np.hstack((one_dim[:, np.newaxis], two_dim))

array([[1, 0, 1],
       [2, 2, 3]])

In [34]:
r = np.array([2, 5, 7, 8, 90, 54, 12])
x1, x2, x3 = np.split(r, [3, 5])
print(x1, x2, x3)

[2 5 7] [ 8 90] [54 12]


In [36]:
x = np.arange(0, 16).reshape((4, 4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
lower, upper = np.vsplit(x, [2])
print(lower)

[[0 1 2 3]
 [4 5 6 7]]


In [39]:
print(upper)

[[ 8  9 10 11]
 [12 13 14 15]]


In [41]:
left, right = np.hsplit(x, [2])
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [42]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

#### vectorization

In [55]:
# unary operations
x = np.array([2, 7, -7, 9])
print('x+:', x + 4)
print('x-:', x - 4)
print('x/:', x / 2)
print('x*:', x * 8)
print('x**:',x ** 2 )
print('xabs',np.abs(x))
print('x//:',x // 2)

x+: [ 6 11 -3 13]
x-: [ -2   3 -11   5]
x/: [ 1.   3.5 -3.5  4.5]
x*: [ 16  56 -56  72]
x**: [ 4 49 49 81]
xabs [2 7 7 9]
x//: [ 1  3 -4  4]


#### All of these arithmetic operations are simply convenient wrappers around specific ufuncs built into NumPy. For example, the + operator is a wrapper for the add ufunc:

### Trigonometric Functions

In [57]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [58]:
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


#### Inverse trigonometric

In [59]:
x = [-1, 0, 1]
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]
