In [5]:
import numpy as np

x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
y = x.reshape((3,3))
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
xh = x.reshape((1, 9))
xh

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [12]:
xv = x.reshape((9, 1))
xv

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [14]:
x_new_h = x[np.newaxis, :]
x_new_h

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [16]:
x_new_v = x[:, np.newaxis]
x_new_v

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [20]:
two_dim = np.arange(0, 4).reshape((2, 2))
two_dim

array([[0, 1],
       [2, 3]])

##### Same dimension Concatenate 

In [21]:
#stack along the first axis
np.concatenate([two_dim, two_dim])

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [23]:
#stack along the second axis
np.concatenate((two_dim, two_dim), axis=1)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

In [45]:
one_dim = np.arange(1, 3)
one_dim

array([1, 2])

In [46]:
np.vstack((one_dim, two_dim))

array([[1, 2],
       [0, 1],
       [2, 3]])

In [30]:
np.hstack((one_dim[:, np.newaxis], two_dim))

array([[1, 0, 1],
       [2, 2, 3]])

In [34]:
r = np.array([2, 5, 7, 8, 90, 54, 12])
x1, x2, x3 = np.split(r, [3, 5])
print(x1, x2, x3)

[2 5 7] [ 8 90] [54 12]


In [36]:
x = np.arange(0, 16).reshape((4, 4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
lower, upper = np.vsplit(x, [2])
print(lower)

[[0 1 2 3]
 [4 5 6 7]]


In [39]:
print(upper)

[[ 8  9 10 11]
 [12 13 14 15]]


In [41]:
left, right = np.hsplit(x, [2])
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [42]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

#### vectorization

In [55]:
# unary operations
x = np.array([2, 7, -7, 9])
print('x+:', x + 4)
print('x-:', x - 4)
print('x/:', x / 2)
print('x*:', x * 8)
print('x**:',x ** 2 )
print('xabs',np.abs(x))
print('x//:',x // 2)

x+: [ 6 11 -3 13]
x-: [ -2   3 -11   5]
x/: [ 1.   3.5 -3.5  4.5]
x*: [ 16  56 -56  72]
x**: [ 4 49 49 81]
xabs [2 7 7 9]
x//: [ 1  3 -4  4]


#### All of these arithmetic operations are simply convenient wrappers around specific ufuncs built into NumPy. For example, the + operator is a wrapper for the add ufunc:

### Trigonometric Functions

In [57]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [58]:
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


#### Inverse trigonometric

In [59]:
x = [-1, 0, 1]
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [62]:
x = [1, 2, 3]
print('x: ', x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3., x))

x:  [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3.  9. 27.]


#### The inverse of the exponentials, the logarithms, are also available. The basic np.log gives the natural logarithm

In [64]:
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [65]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


#### NumPy has many more ufuncs available, including for hyperbolic trigonometry, bit‐ wise arithmetic, comparison operations, conversions from radians to degrees, round‐ ing and remainders, and much more.

In [2]:
import numpy as np
from scipy import special
x = [1, 5, 10]
print("gamma(x) =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2) =", special.beta(x, 2))

gamma(x) = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2) = [0.5        0.03333333 0.00909091]


In [3]:
# Error function (integral of Gaussian),
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x) =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x) = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


### Specifying Output


In [10]:
x = np.array([8, 9, 3, 5])
y = np.empty(4)
np.multiply(x, 3, out=y, dtype='int')

array([24., 27.,  9., 15.])

In [25]:
x = np.arange(1, 8)
y = np.zeros(14)
np.multiply(2, x, out=y[::2])
y

array([ 2.,  0.,  4.,  0.,  6.,  0.,  8.,  0., 10.,  0., 12.,  0., 14.,
        0.])

In [26]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [27]:
np.multiply.reduce(x)

120

In [28]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [29]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

#### Outer Products

##### Multiplication table

In [33]:
x = np.arange(1, 7)
np.multiply.outer(x, x)


array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

In [34]:
y = np.arange(7, 14)
np.multiply.outer(x, y)

array([[ 7,  8,  9, 10, 11, 12, 13],
       [14, 16, 18, 20, 22, 24, 26],
       [21, 24, 27, 30, 33, 36, 39],
       [28, 32, 36, 40, 44, 48, 52],
       [35, 40, 45, 50, 55, 60, 65],
       [42, 48, 54, 60, 66, 72, 78]])